// Mocks generated by Mockito 5.4.6 from annotations
// in app_fe_ecomerce/test/features/chat/domain/usecases/chat_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_fe_ecomerce/core/error/failures.dart' as _i5;
import 'package:app_fe_ecomerce/features/chat/domain/entities/conversation_entity.dart'
    as _i6;
import 'package:app_fe_ecomerce/features/chat/domain/entities/message_entity.dart'
    as _i8;
import 'package:app_fe_ecomerce/features/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.ConversationEntity>>>
  getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i6.ConversationEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.ConversationEntity>>
                  >(this, Invocation.method(#getConversations, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.ConversationEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.MessageEntity>>> getMessages(
    int? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.MessageEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.MessageEntity>>
                  >(this, Invocation.method(#getMessages, [conversationId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.MessageEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.MessageEntity>> sendMessage({
    required int? receiverId,
    required String? content,
    String? type = 'TEXT',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #receiverId: receiverId,
              #content: content,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i8.MessageEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i8.MessageEntity>>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #receiverId: receiverId,
                      #content: content,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.MessageEntity>>);
}
