// Mocks generated by Mockito 5.4.6 from annotations
// in app_fe_ecomerce/test/features/payment/presentation/pages/payment_qr_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_fe_ecomerce/core/error/failures.dart' as _i6;
import 'package:app_fe_ecomerce/core/usecase/usecase.dart' as _i8;
import 'package:app_fe_ecomerce/features/payment/domain/entities/payment_config_entity.dart'
    as _i7;
import 'package:app_fe_ecomerce/features/payment/domain/repositories/payment_repository.dart'
    as _i2;
import 'package:app_fe_ecomerce/features/payment/domain/usecases/get_payment_config_usecase.dart'
    as _i3;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaymentRepository_0 extends _i1.SmartFake
    implements _i2.PaymentRepository {
  _FakePaymentRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPaymentConfigUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPaymentConfigUseCase extends _i1.Mock
    implements _i3.GetPaymentConfigUseCase {
  MockGetPaymentConfigUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PaymentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePaymentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PaymentRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.PaymentConfigEntity>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.PaymentConfigEntity>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.PaymentConfigEntity>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.PaymentConfigEntity>>);
}
