// Mocks generated by Mockito 5.4.6 from annotations
// in app_fe_ecomerce/test/features/chat/data/repositories/chat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_fe_ecomerce/features/chat/data/datasources/chat_remote_datasource.dart'
    as _i3;
import 'package:app_fe_ecomerce/features/chat/data/models/conversation_model.dart'
    as _i5;
import 'package:app_fe_ecomerce/features/chat/data/models/message_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageModel_0 extends _i1.SmartFake implements _i2.MessageModel {
  _FakeMessageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock
    implements _i3.ChatRemoteDataSource {
  MockChatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ConversationModel>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i4.Future<List<_i5.ConversationModel>>.value(
              <_i5.ConversationModel>[],
            ),
          )
          as _i4.Future<List<_i5.ConversationModel>>);

  @override
  _i4.Future<List<_i2.MessageModel>> getMessages(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel> sendMessage({
    required int? receiverId,
    required String? content,
    String? type = 'TEXT',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #receiverId: receiverId,
              #content: content,
              #type: type,
            }),
            returnValue: _i4.Future<_i2.MessageModel>.value(
              _FakeMessageModel_0(
                this,
                Invocation.method(#sendMessage, [], {
                  #receiverId: receiverId,
                  #content: content,
                  #type: type,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MessageModel>);
}
