// Mocks generated by Mockito 5.4.6 from annotations
// in app_fe_ecomerce/test/features/chat/presentation/bloc/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_fe_ecomerce/core/error/failures.dart' as _i6;
import 'package:app_fe_ecomerce/core/services/chat_socket_service.dart' as _i13;
import 'package:app_fe_ecomerce/core/usecase/usecase.dart' as _i8;
import 'package:app_fe_ecomerce/features/chat/data/models/message_model.dart'
    as _i14;
import 'package:app_fe_ecomerce/features/chat/domain/entities/conversation_entity.dart'
    as _i7;
import 'package:app_fe_ecomerce/features/chat/domain/entities/message_entity.dart'
    as _i11;
import 'package:app_fe_ecomerce/features/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:app_fe_ecomerce/features/chat/domain/usecases/get_conversations_usecase.dart'
    as _i3;
import 'package:app_fe_ecomerce/features/chat/domain/usecases/get_messages_usecase.dart'
    as _i10;
import 'package:app_fe_ecomerce/features/chat/domain/usecases/send_message_usecase.dart'
    as _i12;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatRepository_0 extends _i1.SmartFake
    implements _i2.ChatRepository {
  _FakeChatRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetConversationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationsUseCase extends _i1.Mock
    implements _i3.GetConversationsUseCase {
  MockGetConversationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.ConversationEntity>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i7.ConversationEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, List<_i7.ConversationEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.ConversationEntity>>>);
}

/// A class which mocks [GetMessagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessagesUseCase extends _i1.Mock
    implements _i10.GetMessagesUseCase {
  MockGetMessagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i11.MessageEntity>>> call(
    int? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversationId]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i11.MessageEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, List<_i11.MessageEntity>>
                  >(this, Invocation.method(#call, [conversationId])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i11.MessageEntity>>>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i12.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i11.MessageEntity>> call(
    _i12.SendMessageParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i11.MessageEntity>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i11.MessageEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i11.MessageEntity>>);
}

/// A class which mocks [ChatSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSocketService extends _i1.Mock implements _i13.ChatSocketService {
  MockChatSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i14.MessageModel> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<_i14.MessageModel>.empty(),
          )
          as _i4.Stream<_i14.MessageModel>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
